---
name: "AnimeThemes"
guid: "086022b5-29fb-4f89-a298-3d595492a5ed"
version: 5
targetAbi: "10.11.6.0"
framework: "net9.0"
overview: "Plugin for Jellyfin that fetches anime themes (OPs and EDs) from animethemes.moe"
description: >
  Plugin for Jellyfin that fetches anime themes (OPs and EDs) from animethemes.moe.

  **Since the AniDB ID is used to find the matching themes, you'll need to install the AniDB plugin.**

category: "Metadata"
owner: "EusthEnoptEron"
artifacts:
  - "Jellyfin.Plugin.AnimeThemes.dll"
changelog: |-
  - Batch requests to AnimeThemes API (#40) @EusthEnoptEron
